name:                DeBruijn
version:             0.1.0.0
github:              "githubuser/DeBruijn"
license:             BSD3
author:              "Tchowski"
maintainer:          "m.olechowski@epitech.eu"
copyright:           "2019 Tchowski"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/DeBruijn#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  deBruijn:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DeBruijn

tests:
  DeBruijn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DeBruijn
